jboss-set/harmonia

docker-job.sh
OpenJDK8 uses requires an extra folder to be mounted on the docker image to work properly. I also clean up the script a bit to make it a bit more easy to maintain the mount
=> Fix mount jdk8

eap-job.sh
Missed the IPv6 option in initial migration
=> Enable IPv6 in CCI testsuite

umb-build-message.sh
Remove the new lines so that the property can be correctly read in the job
=> Remove new lines from UMB message

pr-processor.sh, tests/pr-processor-test.bats
This is same change as https://github.com/jboss-set/harmonia/pull/40 but for olympus branch, 
This configures 7.4.z stream for pr-processor, and also remove and stop run for old 7.2.z stream (no 7.2.z stream is expected).
Please approve and I will merge and activate it after 7.4.0 is QE sign-off.
=> add 7.4.z stream to pr-processor, remove old 7.2.z

eap-job.sh
CCI jobs are failing on 7.4.x due to a missing `-Drelease` parameter and different `dist` directory name, see
https://eapdev-jenkins-csb-jbossset.apps.ocp4.prod.psi.redhat.com/job/eap-7.4/job/eap-7.4.x-proposed-build/
=> extra build opts and ee-dist for 7.4.x

cryo.sh
Only double quotes `"${CRYO_JAR}"`, do not double quote on values
=> Fix cryo command on passing ${CRYO_COMMAND_ARGS}

eap-job-64.sh, eap-job.sh
`ZIP_WORKSPACE` is set to `false` by default, I think it is intended to not produce `workspace.zip` by default, and only do when it is set to `true`.
This will avoid producing `workspace.zip` for all EAP jobs, and it will save lots of spaces.
=> produce workspace.zip only when ZIP_WORKSPACE is set to true

upgrade-components-report.sh
On Thunder we used local MTA which is not available on Olympus runners, hence we need to configure SMTP server URL.
=> Dependency alignment: make SMTP server URL configurable

tests/tests-suite.sh
Place: `runTests()` function in `tests/tests-suite.sh` 
`${1}` should be `${tests}` to be able to run bats testing to produce the `.tap` files. we may need to add extra checks on the tap report on the tests result in the future.
=> tests_file points to wrong place

eap-job/base.sh
Part of https://projects.engineering.redhat.com/browse/SET-422 
MaxPermSize is not used since JDK8 and was removed later
=> Remove MaxPermSize

eap-job-cci-eap64-testsuite.sh
By externalising the JBoss Developer repository URL
=> Improve flexibility of eap-job-cci-eap64-testsuite.sh

molecule.sh
using pip-3 (alternatives) should be compatible with both python 3.8 (rhel8/aap2.1) and python 3.9 (rhel9/aap2.2)
=> use pip-3 instead of pip-3.8 default

eap-job/base.sh
Minor fix for double slashes in SERVER_URL and SOURCE_URL.
I came across this when I looked at the new pipeline. 
```
BUILD_URL=https://eapdev-jenkins-csb-jbossset.apps.ocp-c1.prod.psi.redhat.com/job/eap-8.0/job/aligned-eap-8.0-build/37/
SERVER_URL=https://eapdev-jenkins-csb-jbossset.apps.ocp-c1.prod.psi.redhat.com/job/eap-8.0/job/aligned-eap-8.0-build/37//artifact/jboss-eap-dist-483eee7.zip
SOURCE_URL=https://eapdev-jenkins-csb-jbossset.apps.ocp-c1.prod.psi.redhat.com/job/eap-8.0/job/aligned-eap-8.0-build/37//artifact/jboss-eap-src-483eee7.zip
```
E.g. https://eapdev-jenkins-csb-jbossset.apps.ocp-c1.prod.psi.redhat.com/job/eap-8.0/job/aligned-eap-8.0-build/37/consoleFull 
The Jenkins `BUILD_URL` env variable described here https://wiki.jenkins.io/display/JENKINS/Building+a+software+projec …
=> Fix double slashes in SERVER_URL and SOURCE_URL

ansible/janus.sh
@guidograzioli updating Harmonia for Janus job to use fqcn_mig instead of janus_legacy (tested on Olympus; works for all the job but jbcs)
=> ansible: migrate janus job to fqcn_mig

eap-job/eap-cci.bat
Issue: https://issues.redhat.com/browse/SET-155
=> SET-155 Create Windows EAP test job on CCI

ansible/molecule/common.sh
@guidograzioli found another issue indeed! This separator is added down the road so this led to have the creds vars replaced by "--"
=> ansible: add missing args sep to molecule cli

eap-job/base.sh, eap-job/cci.sh
Remove redundant step in `post_build()`, already done in `build()`
Also the if condition seems wrong to me when you assign a default value to `ZIP_WORKSPACE` in `base.sh`
`readonly ZIP_WORKSPACE=${ZIP_WORKSPACE:-'false'}`
=> Fix if condition for zip workspace and remove redundant step in build()

ansible/molecule/common.sh
- determine which version of Molecule is being used to assert driver name (mol6 renamed delegated to default)
- add LANG / LC_ALL export to workaround issue specific to Ansible 2.14
=> Rework molecule.sh to works with UBI9

ansible/molecule/common.sh
@guidograzioli FYI
If the slave image is not provided by the job, harmonia will use the molecule version to determine which slave image to use.
=> molecule: allow slave image to be overriden by job

eap-job/cci.sh
Both XP 4 and 5 don't have this testsuite folder.
=> Add optional skip for pre test since the directory doesn't exist in XP

ansible/molecule/molecule.sh
Issue: https://issues.redhat.com/browse/AMW-278
=> AMW-278 Adding JBoss Network API secrets to run Ansible demo successfully
