jboss-set/harmonia

eap-job.sh
tests/eap-job-tests.bats

@spyrkob @iweiss What do you think?

SET-152 - Enhance eap-job.sh to pass extra parameters to the mvn command

---

elytron-web-upgrade-components.sh
wildfly-core-upgrade-components.sh
wildfly-elytron-upgrade-components.sh
wildfly-upgrade-components.sh

https://projects.engineering.redhat.com/browse/SET-150

Adding script for automatic component upgrades on Wildfly

---

tests/tests-common.sh
tests/upgrade-components-report-test.sh
upgrade-components-report.sh

@TomasHofman let me know if you see any issue with the testsuite! If not, I'll merge it to Harmonia and add the test to the harmonia-ci job:
`$ bats -t tests/upgrade-components-report-test.sh `
`1..8`
`ok 1 Test usage`
`ok 2 Test missing email`
`ok 3 Test missing rule name`
`ok 4 Test missing target dir`
`ok 5 Test case: Wildfly Core`
`ok 6 Test case: Elytron Web`
`ok 7 Test case: Wildfly Elytron`
`ok 8 Test case: Wildfly Master`

Add unit tests suite for upgrade-components-report.sh

---

upgrade-components-report.sh

...check if report was generated before sending email

Component upgrade improvements

---

tests/upgrade-components-report-test.bats
upgrade-components-report.sh

* and check also file size before sending an email.

Keep report file until next run

---

upgrade-components-report.sh

* Change logger URL,
* define JAVA_HOME to make sure correct JVM is used.

upgrade-components-report.sh - change logger URL, define $JAVA_HOME

---

eap-installer.sh
eap-job.sh
tests/eap-installer-tests.bats
tests/eap-job-tests.bats
tests/tests-common.sh
tests/umb-build-message-tests.bats
umb-build-message.sh

JIRA: https://projects.engineering.redhat.com/browse/SET-334

[SET-334] Harmonia jobs for installer and UMB notifier

---

eap-installer.sh
eap-job.sh
tests/eap-installer-tests.bats
tests/eap-job-tests.bats
tests/pr-processor-test.bats
tests/tests-common.sh
tests/umb-build-message-tests.bats
umb-build-message.sh

Issue: https://projects.engineering.redhat.com/browse/SET-334

[SET-334] Harmonia changes for running on CCI 

---

eap-installer.sh

Add option to override eap and quickstarts links

Parametrize Installer Testsuite

---

eap-job.sh

Fixes issue where both 7.3 and 7.4 have ee-dist dir, but 7.3 should use dist folder to generate zip

decide on dist dir based on pom

---

cct-job.sh

I'll add testing in a follow-up PR.

Add cct-job.sh

---

upgrade-components-report.sh

* don't reveal SMTP password in debugging mode,
* don't specify any default logger URL - logger won't be used if URL is
not set,
* update usage message.

Component alignment script fixes

---

cryo.sh

Issue: https://issues.redhat.com/browse/SET-358
This PR tried to add `cryo.sh` to run Cryo's job.

[SET-358] Added cryo.sh for Cryo jobs

---

eap-job.sh

Issue: https://issues.redhat.com/browse/SET-405

[SET-405] Adds -Dci-cleanup to EAP 7 test-suite jobs

---

cryo.sh
eap-job-64.sh

Issue: https://issues.redhat.com/browse/SET-403
related: https://github.com/jboss-set/cedalion/pull/7

[SET-403] add default value and var if specified to run as build script

---

.github/workflows/shellcheck.yml

Issue: https://issues.redhat.com/browse/SET-412
This PR tries to define a Github Action to run [bats](https://github.com/bats-core/bats-core) tests using [mig4/setup-bats](https://github.com/marketplace/actions/setup-bats-testing-framework)

[SET-412] Add Github Action for Harmonia

---

upgrade-components-report.sh

Issue: https://issues.redhat.com/browse/SET-469

SET-469 Move component-alignment-config-template.csv.j2 to Cedalion.

---

cryo.sh

Issue: https://issues.redhat.com/browse/SET-447

[SET-447] Update CRYO_HARMONIA_SSH to eap-job/olympus.sh

---

eap-job/base.sh

Revert "Fix VBE jar location"

---

molecule-downstream.sh
molecule.sh

@spyrkob FYI, I'll merge that one when you've approved the Hera's one.

Rework molecule downstream CI

---

molecule.sh

Hard to say if molecule really uses the settings or if it really helps, but at least, it does not break anything.

Ssh kex exchange identification

---

eap-job/base.sh
eap-job/cci.sh
eap-job/olympus.sh

Update VBE to run with EAP8 on CCI

---

ansible/common.sh
ansible/molecule/molecule.sh

@guidograzioli Please review! :)

ansible: ensure all reqs.yml are passed to ansible-galaxy collection install

---

ansible/janus.sh

ansible: migrate janus job to fqcn_mig

---

eap-job/eap-cci.bat

Issue: https://issues.redhat.com/browse/SET-155

SET-155 Check jdk and maven version for Windows EAP test job on CCI

---

ansible/molecule/common.sh

ansible: fixes miss use of double quotes

---

eap-job/eap-cci.bat

Issue: https://issues.redhat.com/browse/SET-155

SET-155 CCI windows IPV6 jobs are failing for JBEAP 7.4 and 8

---

eap-job/eap-cci.bat

Issue: https://issues.redhat.com/browse/SET-155

SET-155 dependency issue resolve

---

ansible/validate-downstream-collection.sh

@guidograzioli remember this weird systemd error with reload? I found a fix for it. Not sure why, but this seems to mitigate the symptom (I've run a ~20 build without running into the issue again. 
Note that I have also added a delay for the broker as the runner job (for AMQ Streams) often fails because the broker is not ready yet.

ansible-runner: fix recurring sysd issue

---

ansible/janus.sh
ansible/molecule/common.sh

@guidograzioli a few stupidity later, this finally works ... Please review! :)

Janus override play

---

eap-job/base.sh

Issue: https://issues.redhat.com/browse/SET-757

SET-757 Check for java and maven executable or not before starting the job.

---

eap-job-64.sh

Issue: https://issues.redhat.com/browse/SET-769

SET-769 CCI having broken EAP6.4 jobs
